

package GUI;




import java.awt.event.ActionListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import Storage.*;
import java.awt.event.ActionEvent;
import java.util.List;
import Exercise.*;
/*
 * window.java
 *
 * Created on 10 mei 2006, 12:44
 */

/**
 *
 * @author  Kurt Deklerck
 */
public class HoofdVenster extends javax.swing.JFrame implements ChangeListener{
    
    private boolean teacherMode;
    private GUImodel gModel;
    //private InlogDialog iDialog;
    private List<String> nameList;
    private Exercise shownExercise;
//    private Exercise shownExercisePanel;

    
    
    
    /** Creates new form window */
    public HoofdVenster(GUImodel model) {
        initComponents();
        //typeNamesList = new ArrayList<String>();
        
        /**
         * registreerd model bij het GUImodel
         */
        gModel = model;
        gModel.addChangeListener(this);
        
        
        /**
         * inlogDialog weergeven
         */
        gModel.showInlogDialog(this);
       
       
//        iDialog = new InlogDialog(this, true);
//        if (iDialog.showInlogDialog()){
//            gModel.setTeacherMode(true);  
//        }else 
//            gModel.setTeacherMode(false);
        
        /**
         * initialiseer mogelijke type menuItems
         */
        initialiseerTypeMenuItems();
       
       
        
        this.setVisible(true);
        
       
        
    }
    
    public void stateChanged(ChangeEvent e){
        editorMenu.setVisible(gModel.getTeacherMode());
        if ( gModel.getShownExercise()!= shownExercise){
            shownExercise= gModel.getShownExercise();
            showExercise(shownExercise);
        }
//        if (gModel.getShownExercisepanel()!= shownExercisePanel){
//            shownExercisePanel = gModel.getShownExercisepanel();
//            
//        }
    }
    
    public void showExercise(Exercise ex){
        //ExercisePanel ePanel = new ePanel(ex.getTitle()), ex.getQuestion(), ex.getAnswerPanel()};
//        gModel.setNewExercisePanel(ePanel);
        //hoofdPaneel = ePanel;
        
    }
    
    /**
     * initialiseer mogelijke type menuItems
     */
    public void initialiseerTypeMenuItems(){
        nameList = gModel.getOefnTypes();
        for (int i = 0 ; i < nameList.size(); i ++){
            javax.swing.JMenuItem item = new javax.swing.JMenuItem(nameList.get(i));
            item.addActionListener(new typeOefnListener());
            nieuweOefnMenu.add(item);
        }
    }
        
       
    
    private class typeOefnListener implements ActionListener{
        public void actionPerformed(ActionEvent e){
            NewExercisePanel newExPanel = gModel.createNewExercisePanel(e);
            hoofdPaneel.add(newExPanel);
            
        }
    }
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        hoofdPaneel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        oefeningMenu = new javax.swing.JMenu();
        OplosMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAllMenuItem = new javax.swing.JMenuItem();
        loadMenuItem = new javax.swing.JMenuItem();
        inlogMenuItem = new javax.swing.JMenuItem();
        editorMenu = new javax.swing.JMenu();
        nieuweOefnMenu = new javax.swing.JMenu();
        aanpasMenuItem = new javax.swing.JMenuItem();
        removeMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        infoMenuItem = new javax.swing.JMenuItem();
        onlineHelpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J-Solve");
        org.jdesktop.layout.GroupLayout hoofdPaneelLayout = new org.jdesktop.layout.GroupLayout(hoofdPaneel);
        hoofdPaneel.setLayout(hoofdPaneelLayout);
        hoofdPaneelLayout.setHorizontalGroup(
            hoofdPaneelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 997, Short.MAX_VALUE)
        );
        hoofdPaneelLayout.setVerticalGroup(
            hoofdPaneelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 784, Short.MAX_VALUE)
        );

        oefeningMenu.setMnemonic('o');
        oefeningMenu.setText("Oefening");
        OplosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OplosMenuItem.setText("Oefening oplossen");
        OplosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oefnOplossen(evt);
            }
        });

        oefeningMenu.add(OplosMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Oefening opslaan");
        saveMenuItem.setEnabled(false);
        oefeningMenu.add(saveMenuItem);

        saveAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        saveAllMenuItem.setText("Alle oefeningen opslaan");
        saveAllMenuItem.setEnabled(false);
        oefeningMenu.add(saveAllMenuItem);

        loadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadMenuItem.setText("Oefeningen laden");
        loadMenuItem.setEnabled(false);
        oefeningMenu.add(loadMenuItem);

        inlogMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        inlogMenuItem.setText("Inloggen");
        inlogMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opnieuwInloggen(evt);
            }
        });

        oefeningMenu.add(inlogMenuItem);

        menuBar.add(oefeningMenu);

        editorMenu.setMnemonic('E');
        editorMenu.setText("Editor");
        nieuweOefnMenu.setText("Cre\u00eber nieuwe oefening");
        editorMenu.add(nieuweOefnMenu);

        aanpasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        aanpasMenuItem.setText("Oefening wijzigen");
        aanpasMenuItem.setEnabled(false);
        editorMenu.add(aanpasMenuItem);

        removeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        removeMenuItem.setText("Oefening verwijderen");
        removeMenuItem.setEnabled(false);
        editorMenu.add(removeMenuItem);

        menuBar.add(editorMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");
        infoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        infoMenuItem.setText("Info");
        helpMenu.add(infoMenuItem);

        onlineHelpMenuItem.setText("Online help raadplegen");
        onlineHelpMenuItem.setEnabled(false);
        helpMenu.add(onlineHelpMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(hoofdPaneel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(hoofdPaneel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oefnOplossen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oefnOplossen
        gModel.showSelectDialog(this);       
    }//GEN-LAST:event_oefnOplossen

    private void opnieuwInloggen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opnieuwInloggen
          gModel.opnieuwInloggen(evt);
//        if (iDialog.showInlogDialog()){
//            gModel.setTeacherMode(true);  
//        }else 
//            gModel.setTeacherMode(false);
    }//GEN-LAST:event_opnieuwInloggen
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }
    

    
    
    
    
//////////////////////////////////////////
//                                      //
//            Listeners                 //
//                                      //
//////////////////////////////////////////
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OplosMenuItem;
    private javax.swing.JMenuItem aanpasMenuItem;
    private javax.swing.JMenu editorMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel hoofdPaneel;
    private javax.swing.JMenuItem infoMenuItem;
    private javax.swing.JMenuItem inlogMenuItem;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu nieuweOefnMenu;
    private javax.swing.JMenu oefeningMenu;
    private javax.swing.JMenuItem onlineHelpMenuItem;
    private javax.swing.JMenuItem removeMenuItem;
    private javax.swing.JMenuItem saveAllMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
    
}

       




















