/*
 * NewExercisPanel.java
 *
 * Created on 15 mei 2006, 0:50
 */

package GUI;

import Exercise.MultichoiceExercise;

/**
 *
 * @author  Kurt Deklerck
 */
public class NewExercisePanel extends javax.swing.JPanel {
    
    private GUImodel gModel;
    private MultichoiceExercise mEx;
    /** Creates new form NewExercisPanel */
    public NewExercisePanel(GUImodel guiModel, MultichoiceExercise mExercise) {
        initComponents();
        gModel = guiModel; 
        mEx = mExercise;
        
        
        /**
         *  Hardcoded:  MultichoiceExercise
         */
        mEx.drawAddPanel(antwoordPanel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        titelLabel = new javax.swing.JLabel();
        themaLabel = new javax.swing.JLabel();
        vraagLabel = new javax.swing.JLabel();
        themaBox = new javax.swing.JComboBox();
        titleTextField = new javax.swing.JTextField();
        antwoordPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vraagTextArea = new javax.swing.JTextArea();
        antwoordLabel = new javax.swing.JLabel();
        toevoegButton = new javax.swing.JButton();

        titelLabel.setText("Titel:");

        themaLabel.setText("Thema:");

        vraagLabel.setText("Vraag:");

        themaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "algemeen", "java exceptions", "java syntax", "C++ syntax", "GUI" }));

        org.jdesktop.layout.GroupLayout antwoordPanelLayout = new org.jdesktop.layout.GroupLayout(antwoordPanel);
        antwoordPanel.setLayout(antwoordPanelLayout);
        antwoordPanelLayout.setHorizontalGroup(
            antwoordPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 805, Short.MAX_VALUE)
        );
        antwoordPanelLayout.setVerticalGroup(
            antwoordPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 292, Short.MAX_VALUE)
        );

        vraagTextArea.setColumns(20);
        vraagTextArea.setRows(5);
        jScrollPane1.setViewportView(vraagTextArea);

        antwoordLabel.setText("Antwoord:");

        toevoegButton.setText("Toevoegen");
        toevoegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oefeningToevoegen(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(antwoordPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(titelLabel)
                            .add(themaLabel))
                        .add(26, 26, 26)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(themaBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(titleTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(vraagLabel)
                        .add(26, 26, 26)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(antwoordLabel)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(312, 312, 312)
                .add(toevoegButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .add(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titelLabel)
                    .add(titleTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(themaLabel)
                    .add(themaBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(vraagLabel)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(antwoordLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(antwoordPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(toevoegButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oefeningToevoegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oefeningToevoegen
        /**
         * TODO nog extra gegevens doorzenden
         */ 
        gModel.saveNewExercise(titleTextField.getText(), (String) themaBox.getSelectedItem(), vraagTextArea.getText());
    }//GEN-LAST:event_oefeningToevoegen
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antwoordLabel;
    private javax.swing.JPanel antwoordPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox themaBox;
    private javax.swing.JLabel themaLabel;
    private javax.swing.JLabel titelLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JButton toevoegButton;
    private javax.swing.JLabel vraagLabel;
    private javax.swing.JTextArea vraagTextArea;
    // End of variables declaration//GEN-END:variables
    
}
